name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_XAjmXVr94iRAVVeYOf9b54iTpAt4/iFx17KtPkS"
          echo "Deployment triggered!"
